export const MARKET_UPDATED_AT = 'Septiembre 2026';

export const MARKET_ASSUMPTIONS = {
  region: 'Colombia',
  currency: 'COP',
  kwhPrice: 850,
  laborRate: 18000,
  machineHour: 2200,
  setupFee: 9000,
  minimumOrder: 25000,
  failureRate: 8,
  wastePercent: 12,
  targetMargin: 36,
  sourceLabel: 'Referencias Colombia: filamento retail, energía regulada/comercial y servicios FDM publicados',
};

export const MATERIALS = {
  PLA: {
    value: 'PLA',
    label: 'PLA',
    watts: 95,
    marketRollPrice: 80000,
    marketGramPrice: 95,
    marketMinuteRate: 420,
    marketFactor: 1,
    failureRate: 7,
    wastePercent: 10,
    note: 'Económico, rápido y muy competitivo para prototipos, decoración y piezas de uso general.',
  },
  PETG: {
    value: 'PETG',
    label: 'PETG',
    watts: 110,
    marketRollPrice: 88000,
    marketGramPrice: 115,
    marketMinuteRate: 480,
    marketFactor: 1.12,
    failureRate: 8,
    wastePercent: 12,
    note: 'Más resistente y durable que PLA; buena opción para piezas funcionales.',
  },
  TPU: {
    value: 'TPU',
    label: 'TPU',
    watts: 105,
    marketRollPrice: 118000,
    marketGramPrice: 155,
    marketMinuteRate: 620,
    marketFactor: 1.32,
    failureRate: 12,
    wastePercent: 15,
    note: 'Flexible, lento y más delicado de imprimir; debe cobrarse con prima técnica.',
  },
  ABS: {
    value: 'ABS',
    label: 'ABS',
    watts: 140,
    marketRollPrice: 98000,
    marketGramPrice: 135,
    marketMinuteRate: 560,
    marketFactor: 1.22,
    failureRate: 11,
    wastePercent: 15,
    note: 'Resistente al calor e impacto; requiere control térmico y mayor riesgo de falla.',
  },
  ASA: {
    value: 'ASA',
    label: 'ASA',
    watts: 135,
    marketRollPrice: 165000,
    marketGramPrice: 190,
    marketMinuteRate: 620,
    marketFactor: 1.38,
    failureRate: 12,
    wastePercent: 16,
    note: 'Premium para exteriores y UV; el material y el control de impresión elevan el precio.',
  },
};

export const QUICK_PRESETS = {
  economy: {
    label: 'Competitivo',
    description: 'Para piezas simples y clientes sensibles al precio.',
    values: {
      materialType: 'PLA',
      modelComplexity: 'simple',
      printMode: 'speed',
      infillDensity: 14,
      wastePercent: 10,
      failureRate: 6,
      quantity: 1,
      rollPrice: 72000,
      rollWeight: 1000,
      usedGrams: 80,
      printHours: 0.9,
      printerPower: 95,
      kwhPrice: 780,
      machineHour: 1800,
      laborRate: 15000,
      setupMinutes: 10,
      postProcessMinutes: 8,
      extras: 5000,
      targetMargin: 28,
      roundTo: 500,
      validityDays: 5,
      deliveryDays: 4,
      deliveryMethod: 'Retiro o domicilio coordinado',
      paymentTerms: 'Pago contra entrega',
      notes: 'Precio optimizado para piezas sencillas. No incluye rediseño del modelo.',
    },
  },
  standard: {
    label: 'Profesional',
    description: 'Balance entre costo real, mercado y utilidad sana.',
    values: {
      materialType: 'PLA',
      modelComplexity: 'medium',
      printMode: 'standard',
      infillDensity: 18,
      wastePercent: 12,
      failureRate: 8,
      quantity: 1,
      rollPrice: 80000,
      rollWeight: 1000,
      usedGrams: 140,
      printHours: 1.6,
      printerPower: 95,
      kwhPrice: 850,
      machineHour: 2200,
      laborRate: 18000,
      setupMinutes: 15,
      postProcessMinutes: 12,
      extras: 8000,
      targetMargin: 36,
      roundTo: 1000,
      validityDays: 7,
      deliveryDays: 3,
      deliveryMethod: 'Domicilio o retiro',
      paymentTerms: '50% anticipo y 50% contra entrega',
      notes: 'Incluye revisión del archivo, preparación, impresión, control visual y empaque básico.',
    },
  },
  premium: {
    label: 'Alta calidad',
    description: 'Detalle, baja tolerancia a fallas y mejor acabado.',
    values: {
      materialType: 'PETG',
      modelComplexity: 'complex',
      printMode: 'premium',
      infillDensity: 24,
      wastePercent: 14,
      failureRate: 10,
      quantity: 1,
      rollPrice: 88000,
      rollWeight: 1000,
      usedGrams: 180,
      printHours: 2.4,
      printerPower: 110,
      kwhPrice: 900,
      machineHour: 2600,
      laborRate: 24000,
      setupMinutes: 22,
      postProcessMinutes: 25,
      extras: 14000,
      targetMargin: 42,
      roundTo: 1000,
      validityDays: 7,
      deliveryDays: 5,
      deliveryMethod: 'Entrega programada',
      paymentTerms: '50% anticipo y saldo al entregar',
      notes: 'Incluye ajuste fino, inspección visual, limpieza de pieza y acabado premium básico.',
    },
  },
};

export const MODEL_COMPLEXITY_OPTIONS = [
  { label: 'Simple', value: 'simple' },
  { label: 'Media', value: 'medium' },
  { label: 'Compleja', value: 'complex' },
];

export const PRINT_MODE_OPTIONS = [
  { label: 'Rápido', value: 'speed' },
  { label: 'Estándar', value: 'standard' },
  { label: 'Detalle fino', value: 'detail' },
  { label: 'Máxima calidad', value: 'premium' },
];

export const MATERIAL_OPTIONS = Object.values(MATERIALS).map((material) => ({
  label: `${material.label} - ref. ${material.marketRollPrice.toLocaleString('es-CO')} COP/kg`,
  value: material.value,
}));

export const ROUND_OPTIONS = [
  { label: '$500', value: 500 },
  { label: '$1.000', value: 1000 },
  { label: '$2.000', value: 2000 },
  { label: '$5.000', value: 5000 },
];

export const PRICE_TYPE_OPTIONS = [
  { label: 'Mínimo rentable', value: 'minimum' },
  { label: 'Recomendado', value: 'recommended' },
  { label: 'Premium', value: 'premium' },
  { label: 'Personalizado', value: 'custom' },
];

export const DEFAULT_FORM = {
  businessName: 'JPrinter3D',
  businessSubtitle: 'Impresión 3D personalizada',
  contactInfo: 'WhatsApp +57 300 000 0000',
  documentType: 'quote',
  quoteName: 'Pieza personalizada',
  clientName: 'Cliente por confirmar',
  quantity: 1,
  materialType: 'PLA',
  modelComplexity: 'medium',
  printMode: 'standard',
  infillDensity: 18,
  wastePercent: 12,
  failureRate: 8,
  rollPrice: 80000,
  rollWeight: 1000,
  usedGrams: 140,
  printHours: 1.6,
  printerPower: 95,
  kwhPrice: 850,
  machineHour: 2200,
  laborRate: 18000,
  setupMinutes: 15,
  postProcessMinutes: 12,
  extras: 8000,
  targetProfit: 0,
  targetMargin: 36,
  roundTo: 1000,
  priceType: 'recommended',
  customPrice: 0,
  deliveryDays: 3,
  validityDays: 7,
  deliveryMethod: 'Domicilio o retiro',
  paymentTerms: '50% anticipo y 50% contra entrega',
  notes: 'Incluye revisión del archivo, preparación, impresión, control visual y empaque básico.',
};

export const EMPTY_FORM = {
  ...DEFAULT_FORM,
  contactInfo: '',
  quoteName: '',
  clientName: '',
  rollPrice: 0,
  rollWeight: 0,
  usedGrams: 0,
  printHours: 0,
  kwhPrice: 0,
  machineHour: 0,
  laborRate: 0,
  setupMinutes: 0,
  postProcessMinutes: 0,
  extras: 0,
  targetProfit: 0,
  deliveryDays: 0,
  validityDays: 0,
  deliveryMethod: '',
  paymentTerms: '',
  notes: '',
};

export const STORAGE_KEY = 'jprinter3d:calculator:v7';
export const THEME_STORAGE_KEY = 'jprinter3d:theme';
